import { db } from '@/db';
import { transactions } from '@/db/schema';

async function main() {
    const now = new Date();
    const oneMonthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    
    const sampleTransactions = [
        // Salary Deposit - Week 1
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 1,
            date: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000),
            amount: 3500.00,
            description: 'Payroll Deposit - Acme Corp',
            merchant: 'Acme Corporation',
            type: 'credit',
            categoryId: 1,
            pending: false,
            createdAt: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000),
        },
        // Rent Payment - Week 1
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 1,
            date: new Date(now.getTime() - 27 * 24 * 60 * 60 * 1000),
            amount: -1350.00,
            description: 'Monthly Rent Payment',
            merchant: 'Sunset Apartments',
            type: 'debit',
            categoryId: 8,
            pending: false,
            createdAt: new Date(now.getTime() - 27 * 24 * 60 * 60 * 1000),
        },
        // Grocery Shopping - Week 1
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 1,
            date: new Date(now.getTime() - 26 * 24 * 60 * 60 * 1000),
            amount: -87.45,
            description: 'Groceries',
            merchant: 'Safeway #4521',
            type: 'debit',
            categoryId: 3,
            pending: false,
            createdAt: new Date(now.getTime() - 26 * 24 * 60 * 60 * 1000),
        },
        // Coffee Shop - Week 1
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 2,
            date: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000),
            amount: -12.35,
            description: 'Coffee and Pastry',
            merchant: 'Starbucks #8942',
            type: 'debit',
            categoryId: 4,
            pending: false,
            createdAt: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000),
        },
        // Electric Bill - Week 1
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 1,
            date: new Date(now.getTime() - 24 * 24 * 60 * 60 * 1000),
            amount: -134.67,
            description: 'Electricity Bill',
            merchant: 'Pacific Electric',
            type: 'debit',
            categoryId: 9,
            pending: false,
            createdAt: new Date(now.getTime() - 24 * 24 * 60 * 60 * 1000),
        },
        // Gas Station - Week 1
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 2,
            date: new Date(now.getTime() - 23 * 24 * 60 * 60 * 1000),
            amount: -45.20,
            description: 'Gasoline',
            merchant: 'Shell Station',
            type: 'debit',
            categoryId: 6,
            pending: false,
            createdAt: new Date(now.getTime() - 23 * 24 * 60 * 60 * 1000),
        },
        // Freelance Income - Week 2
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 3,
            date: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000),
            amount: 850.00,
            description: 'Web Design Project',
            merchant: 'Creative Solutions LLC',
            type: 'credit',
            categoryId: 1,
            pending: false,
            createdAt: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000),
        },
        // Amazon Purchase - Week 2
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 2,
            date: new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000),
            amount: -156.78,
            description: 'Online Purchase',
            merchant: 'Amazon.com',
            type: 'debit',
            categoryId: 5,
            pending: false,
            createdAt: new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000),
        },
        // Restaurant Dinner - Week 2
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 1,
            date: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000),
            amount: -42.15,
            description: 'Dinner',
            merchant: 'The Local Bistro',
            type: 'debit',
            categoryId: 4,
            pending: false,
            createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000),
        },
        // Internet Bill - Week 2
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 1,
            date: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000),
            amount: -89.99,
            description: 'Internet Service',
            merchant: 'Xfinity',
            type: 'debit',
            categoryId: 9,
            pending: false,
            createdAt: new Date(now.getTime() - 19 * 24 * 60 * 60 * 1000),
        },
        // Grocery Shopping - Week 2
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 2,
            date: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000),
            amount: -132.67,
            description: 'Weekly Groceries',
            merchant: 'Whole Foods Market',
            type: 'debit',
            categoryId: 3,
            pending: false,
            createdAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000),
        },
        // Netflix Subscription - Week 2
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 1,
            date: new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000),
            amount: -15.99,
            description: 'Netflix Subscription',
            merchant: 'Netflix.com',
            type: 'debit',
            categoryId: 7,
            pending: false,
            createdAt: new Date(now.getTime() - 17 * 24 * 60 * 60 * 1000),
        },
        // Chipotle Lunch - Week 3
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 2,
            date: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000),
            amount: -14.75,
            description: 'Lunch',
            merchant: 'Chipotle Mexican Grill',
            type: 'debit',
            categoryId: 4,
            pending: false,
            createdAt: new Date(now.getTime() - 16 * 24 * 60 * 60 * 1000),
        },
        // Salary Deposit - Week 3
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 1,
            date: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000),
            amount: 3500.00,
            description: 'Payroll Deposit - Acme Corp',
            merchant: 'Acme Corporation',
            type: 'credit',
            categoryId: 1,
            pending: false,
            createdAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000),
        },
        // Target Shopping - Week 3
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 3,
            date: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000),
            amount: -78.93,
            description: 'Household Items',
            merchant: 'Target #1847',
            type: 'debit',
            categoryId: 5,
            pending: false,
            createdAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000),
        },
        // Uber Ride - Week 3
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 2,
            date: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000),
            amount: -23.45,
            description: 'Uber Trip',
            merchant: 'Uber Technologies',
            type: 'debit',
            categoryId: 6,
            pending: false,
            createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000),
        },
        // Pharmacy - Week 3
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 1,
            date: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000),
            amount: -34.67,
            description: 'Prescription Medication',
            merchant: 'CVS Pharmacy',
            type: 'debit',
            categoryId: 10,
            pending: false,
            createdAt: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000),
        },
        // Grocery Shopping - Week 3
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 2,
            date: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
            amount: -95.23,
            description: 'Groceries',
            merchant: 'Trader Joes',
            type: 'debit',
            categoryId: 3,
            pending: false,
            createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000),
        },
        // Phone Bill - Week 3
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 1,
            date: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000),
            amount: -95.00,
            description: 'Mobile Phone Service',
            merchant: 'Verizon Wireless',
            type: 'debit',
            categoryId: 9,
            pending: false,
            createdAt: new Date(now.getTime() - 9 * 24 * 60 * 60 * 1000),
        },
        // Movie Theater - Week 4
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 2,
            date: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000),
            amount: -28.50,
            description: 'Movie Tickets',
            merchant: 'AMC Theaters',
            type: 'debit',
            categoryId: 7,
            pending: false,
            createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000),
        },
        // Freelance Income - Week 4
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 3,
            date: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
            amount: 1200.00,
            description: 'Logo Design Project',
            merchant: 'TechStart Inc',
            type: 'credit',
            categoryId: 1,
            pending: false,
            createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000),
        },
        // Clothing Store - Week 4
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 4,
            date: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000),
            amount: -145.67,
            description: 'Clothing Purchase',
            merchant: 'H&M',
            type: 'debit',
            categoryId: 5,
            pending: false,
            createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000),
        },
        // Doctor Visit - Week 4
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 1,
            date: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
            amount: -125.00,
            description: 'Medical Consultation',
            merchant: 'Downtown Medical Center',
            type: 'debit',
            categoryId: 10,
            pending: false,
            createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000),
        },
        // Gas Station - Week 4
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 2,
            date: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
            amount: -52.30,
            description: 'Gasoline',
            merchant: 'Chevron',
            type: 'debit',
            categoryId: 6,
            pending: false,
            createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000),
        },
        // Restaurant - Week 4
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 5,
            date: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
            amount: -36.85,
            description: 'Dinner with Friends',
            merchant: 'Olive Garden',
            type: 'debit',
            categoryId: 4,
            pending: false,
            createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
        },
        // Amazon Purchase - Recent
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 2,
            date: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
            amount: -89.99,
            description: 'Electronics',
            merchant: 'Amazon.com',
            type: 'debit',
            categoryId: 5,
            pending: false,
            createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
        },
        // Spotify Subscription - Recent
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 1,
            date: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
            amount: -9.99,
            description: 'Music Streaming',
            merchant: 'Spotify',
            type: 'debit',
            categoryId: 7,
            pending: false,
            createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000),
        },
        // Pending Lyft Ride - Today
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 2,
            date: now,
            amount: -18.75,
            description: 'Lyft Ride',
            merchant: 'Lyft Inc',
            type: 'debit',
            categoryId: 6,
            pending: true,
            createdAt: now,
        },
        // Pending Coffee Purchase - Today
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 2,
            date: now,
            amount: -5.85,
            description: 'Coffee',
            merchant: 'Local Coffee House',
            type: 'debit',
            categoryId: 4,
            pending: true,
            createdAt: now,
        }
    ];

    await db.insert(transactions).values(sampleTransactions);
    
    console.log('✅ Transactions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});